version: '3.8'

services:
  # API Gateway Service
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - JWT_SECRET=supersecretkey
    depends_on:
      - postgres

  # UI Application Service
  ui-app:
    build: ./ui-app
    container_name: ui-app
    ports:
      - "3000:3000"
    environment:
      - API_GATEWAY_URL=http://api-gateway:8000
    depends_on:
      - api-gateway

  # API Application Service
  api-app:
    build: ./api-app
    container_name: api-app
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    depends_on:
      - postgres

  # PostgreSQL Database Service
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Volumes for persistent data storage
volumes:
  postgres_data:
