version: '3.8'

services:
# For API-Getway....
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - JWT_SECRET=supersecretkey
    depends_on:
      - db

# For UI-APP [ FrontEnd ] ...
  ui-app:
    build: ./ui-app
    ports:
      - "3000:3000"
    environment:
      - API_GATEWAY_URL=http://api-gateway:8000
    depends_on:
      - api-gateway

  api-app:
    build: ./api-app
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    depends_on:
      - db

# For Database [ DB ] ...
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
