name: Combined Pipeline
on:
  workflow_dispatch:
jobs:
  combined-deploy:
    runs-on: ubuntu-latest
    needs: [db-pipeline, api-pipeline, ui-pipeline]
    steps:
      - name: Trigger DB Migrations
        run: |
          curl -X POST http://api-gateway:8000/trigger-pipeline -H "Content-Type: application/json" -d '{"service": "db", "version": "latest"}'

      - name: Trigger API Pipeline
        run: |
          curl -X POST http://api-gateway:8000/trigger-pipeline -H "Content-Type: application/json" -d '{"service": "api", "version": "latest"}'

      - name: Trigger UI Pipeline
        run: |
          curl -X POST http://api-gateway:8000/trigger-pipeline -H "Content-Type: application/json" -d '{"service": "ui", "version": "latest"}'
