name: UI Pipeline
on:
  workflow_dispatch:
jobs:
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml build ui-app
          docker-compose -f docker-compose.yml up -d ui-app

      - name: Trigger API Gateway
        run: |
          curl -X POST http://api-gateway:8000/trigger-pipeline -H "Content-Type: application/json" -d '{"service": "ui", "version": "latest"}'
